## 奇异值分解
***
***
Time: 2020-09-11<br>
Author: dsy
***

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,0,0,0],
    [0,0,0,4],
    [0,3,0,0],
    [0,0,0,0],
    [2,0,0,0]
])

In [3]:
np.linalg.svd(A)

(array([[ 0.        ,  0.        , -0.4472136 ,  0.        , -0.89442719],
        [-1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        , -0.89442719,  0.        ,  0.4472136 ]]),
 array([ 4.        ,  3.        ,  2.23606798, -0.        ]),
 array([[-0., -0., -0., -1.],
        [-0., -1., -0., -0.],
        [-1., -0., -0., -0.],
        [-0., -0., -1., -0.]]))