## 提升方法
***
***
Time: 2020-09-12<br>
Author: dsy
***

In [1]:
import numpy as np

In [2]:
def AdaBoost(X,Y,V):
    def GM(x,v):
        return 1 if x < v else -1

    
    def I(g,y):
        return 1 if g != y else 0
    
    
    N = len(X)
    D = np.array([1./ N for i in range(N)])
    alpha = []
    for v in V:
        em = sum([D[i] * I(GM(X[i],v),Y[i]) for i in range(N)])
        
#         print([GM(X[i],v)  for i in range(N)])
#         print([Y[i] for i in range(N)])
#         print([D[i] * I(GM(X[i],v),Y[i]) for i in range(N)])
        
        am = 0.5 * np.log((1-em)/em)
        zm = sum([D[i] * np.exp(- am * Y[i] * GM(X[i],v)) for i in range(N)])
        D = [ D[i]/zm * np.exp(- am * Y[i] * GM(X[i],v))  for i in range(N)]
        alpha.append([am,v])
        
#         print("em:",em,"am:",am,"D:",D,"\n","=="*30)
    return alpha
        

In [3]:
X = np.array([
    0,1,2,3,4,5,6,7,8,9
])
Y = np.array([
    1,1,1,-1,-1,-1,1,1,1,-1
])

In [4]:
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
Y

array([ 1,  1,  1, -1, -1, -1,  1,  1,  1, -1])

In [6]:
V = np.array([2.5, 8.5, 5.5])
V

array([2.5, 8.5, 5.5])

In [7]:
AdaBoost(X,Y,V)

[[0.4236489301936017, 2.5],
 [0.6496414920651304, 8.5],
 [-0.7520386983881375, 5.5]]